## Sidhdi Vijay K 22MIC0168 Lab-14

## 1. Handling CSV Files (built-in `csv` module)

### Writing a CSV file using `csv.writer()`

In [1]:
import csv

# Sample data
students = [
    ["Name", "Age", "Parents Income"],
    ["Arun", 21, "5L"],
    ["Priya", 22, "9.2L"],
    ["Kiran", 20, "7.5L"]
]

# Write CSV file
with open("students.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(students)

print("students.csv created in current working directory")

students.csv created in current working directory


### Reading the CSV file using `csv.reader()`

In [2]:
import csv

with open('students.csv', newline='') as f:
    reader = csv.reader(f, delimiter=',')
    for row in reader:
        print(row)

['Name', 'Age', 'Parents Income']
['Arun', '21', '5L']
['Priya', '22', '9.2L']
['Kiran', '20', '7.5L']


### Appending a row to the CSV file

In [3]:
from csv import writer

new_row = ["William", 28, "UAE"]
with open('students.csv', 'a', newline='') as f:
    w = writer(f)
    w.writerow(new_row)

print('Appended a row to students.csv')

Appended a row to students.csv


## 2. Handling CSV with Pandas

Pandas simplifies I/O and data manipulation. Below: create, read, append using pandas.

In [4]:
import pandas as pd

# Create DataFrame and write to CSV
data = {
    'Name': ['Arun', 'Priya', 'Kiran'],
    'Age': [21, 22, 20],
    'Marks': [85, 90, 78]
}

df = pd.DataFrame(data)
df.to_csv('students_pandas.csv', index=False)
print('students_pandas.csv created')

# Read it back
print('\nReading students_pandas.csv:')
print(pd.read_csv('students_pandas.csv'))

# Append a new row (concat) and save
new_row = {'Name':'William','Age':28,'Marks':92}
df_updated = pd.concat([pd.read_csv('students_pandas.csv'), pd.DataFrame([new_row])], ignore_index=True)
df_updated.to_csv('students_pandas.csv', index=False)
print('\nAppended new row and saved students_pandas.csv')
print(pd.read_csv('students_pandas.csv'))

students_pandas.csv created

Reading students_pandas.csv:
    Name  Age  Marks
0   Arun   21     85
1  Priya   22     90
2  Kiran   20     78

Appended new row and saved students_pandas.csv
      Name  Age  Marks
0     Arun   21     85
1    Priya   22     90
2    Kiran   20     78
3  William   28     92


## 3. Handling JSON Files

Using Python's built-in `json` module and Pandas for JSON I/O.

In [5]:
import json

employees = {
    'emp1': {'name':'Lisa','designation':'Programmer','age':34,'salary':54000},
    'emp2': {'name':'Elis','designation':'Trainee','age':24,'salary':40000}
}

with open('employees.json', 'w') as f:
    json.dump(employees, f, indent=4)

print('employees.json written')

# Read it back
with open('employees.json','r') as f:
    data = json.load(f)
print('\nLoaded JSON:')
print(data)

employees.json written

Loaded JSON:
{'emp1': {'name': 'Lisa', 'designation': 'Programmer', 'age': 34, 'salary': 54000}, 'emp2': {'name': 'Elis', 'designation': 'Trainee', 'age': 24, 'salary': 40000}}


### JSON with Pandas

In [6]:
import pandas as pd

people = [
    {'id':1,'name':'Alice','age':25,'city':'New York'},
    {'id':2,'name':'Bob','age':30,'city':'Los Angeles'},
    {'id':3,'name':'Charlie','age':35,'city':'Chicago'}
]

df_people = pd.DataFrame(people)
df_people.to_json('people.json', orient='records', indent=4)
print('people.json created')

print('\nRead back with pandas:')
print(pd.read_json('people.json'))

people.json created

Read back with pandas:
   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago


## 4. Handling Excel Files

Demonstration using `openpyxl` (for direct Excel operations) and Pandas (convenient).

In [7]:
try:
    import openpyxl
except Exception as e:
    print('openpyxl not installed; installing now...')
    !pip install openpyxl --quiet
    import openpyxl

from openpyxl import Workbook
wb = Workbook()
ws = wb.active
ws.title = 'SampleData'
ws['A1'] = 'Name'
ws['B1'] = 'Age'
ws.append(['Arun', 21])
ws.append(['Priya', 22])
wb.save('sample_openpyxl.xlsx')
print('sample_openpyxl.xlsx created')

openpyxl not installed; installing now...
sample_openpyxl.xlsx created


### Excel with Pandas

In [8]:
import pandas as pd

df = pd.DataFrame({'Name':['Arun','Priya','Kiran'],'Age':[21,22,20]})
df.to_excel('sample_pandas.xlsx', sheet_name='Sheet1', index=False)
print('sample_pandas.xlsx written')

print('\nRead it back:')
print(pd.read_excel('sample_pandas.xlsx', sheet_name='Sheet1'))

sample_pandas.xlsx written

Read it back:
    Name  Age
0   Arun   21
1  Priya   22
2  Kiran   20


## 5. NumPy Basics (arrays, indexing, slicing, reshaping)

NumPy provides fast n-dimensional arrays and vectorized operations.

In [10]:
import numpy as np

# Create array
arr = np.array([[1,2,3],[4,5,6]])
print('Array:\n', arr)

# Attributes
print('\nShape:', arr.shape)
print('Dtype:', arr.dtype)

# Indexing & slicing
print('\narr[0,1] =', arr[0,1])
print('First row:', arr[0])

# Reshape
print('\nFlatten then reshape to (3,2):')
print(arr.flatten().reshape(3,2))

Array:
 [[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dtype: int64

arr[0,1] = 2
First row: [1 2 3]

Flatten then reshape to (3,2):
[[1 2]
 [3 4]
 [5 6]]
