## Sidhdi Vijay K 22MIC0168 Lab-13

# NumPy Practice Notebook


In [4]:
# Import NumPy and set a random seed for reproducibility
import numpy as np
np.random.seed(0)
print('NumPy version:', np.__version__)

NumPy version: 2.2.6


## 1) Basic array creation
Examples: `np.array`, `np.eye`, `np.linspace`, `np.arange`, `np.zeros`, `np.ones`, `np.full`.

In [5]:
# 1. Creating a NumPy array using np.array()
arr = np.array([10, 20, 30, 40, 50])
print('np.array ->', arr)

# 2. Identity matrix with np.eye()
eye_mat = np.eye(3)
print('\nnp.eye ->\n', eye_mat)

# 3. Evenly spaced values with np.linspace()
lin_vals = np.linspace(1, 5, 9)
print('\nnp.linspace ->', lin_vals)

# 4. Sequential numbers with np.arange()
arange_vals = np.arange(2, 15, 3)  # start, stop (exclusive), step
print('\nnp.arange ->', arange_vals)

# 5. Array of zeros using np.zeros()
zero_matrix = np.zeros((2, 6))
print('\nnp.zeros ->\n', zero_matrix)

# 6. Array of ones using np.ones()
ones_matrix = np.ones((4, 2))
print('\nnp.ones ->\n', ones_matrix)

# 7. Constant value array using np.full()
const_array = np.full((3, 5), 9)
print('\nnp.full ->\n', const_array)

np.array -> [10 20 30 40 50]

np.eye ->
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.linspace -> [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

np.arange -> [ 2  5  8 11 14]

np.zeros ->
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

np.ones ->
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

np.full ->
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


## 2) Random numbers & index grids
`np.random.rand`, `np.random.randint`, and `np.indices`.

In [6]:
# 8. Random floats between 0 and 1 using np.random.rand()
random_floats = np.random.rand(3, 2)
print('np.random.rand ->\n', random_floats)

# 9. Random integers with np.random.randint()
random_ints = np.random.randint(5, 50, size=(2, 4))
print('\nnp.random.randint ->\n', random_ints)

# 10. Creating index grids with np.indices()
grid_idx = np.indices((2, 3))
print('\nnp.indices ->\n', grid_idx)

np.random.rand ->
 [[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]

np.random.randint ->
 [[41 28 11 29]
 [29 17  6 43]]

np.indices ->
 [[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


## 3) Array properties, reshape and transpose

In [7]:
# 11. Array properties
print('Dimensions (ndim):', arr.ndim)
print('Number of elements (size):', arr.size)
print('Shape (rows, cols):', arr.shape)

# 12. Reshaping with np.reshape()
reshaped_arr = np.arange(16).reshape(4, 4)
print('\nnp.reshape ->\n', reshaped_arr)

# 13. Transpose of matrix using .T
transposed_arr = reshaped_arr.T
print('\nTranspose ->\n', transposed_arr)

Dimensions (ndim): 1
Number of elements (size): 5
Shape (rows, cols): (5,)

np.reshape ->
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Transpose ->
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


## 4) Math operations and statistics
`sum`, `mean`, `max`, `min`, `std`. 

In [8]:
# 14. Basic mathematical operations
nums = np.array([2, 4, 6, 8, 10])
print('Sum:', np.sum(nums))
print('Average:', np.mean(nums))
print('Maximum:', np.max(nums))
print('Minimum:', np.min(nums))
print('Std Deviation:', np.std(nums))

Sum: 30
Average: 6.0
Maximum: 10
Minimum: 2
Std Deviation: 2.8284271247461903


## 5) Diagonal matrix, flattening, sorting and unique values

In [9]:
# 15. Creating a diagonal matrix with np.diag()
diag_matrix = np.diag([4, 8, 12])
print('np.diag ->\n', diag_matrix)

# 16. Flattening array using np.ravel()
flat_arr = reshaped_arr.ravel()
print('\nnp.ravel ->', flat_arr)

# 17. Sorting arrays with np.sort()
unsorted = np.array([12, 4, 9, 1, 7])
sorted_output = np.sort(unsorted)
print('\nnp.sort ->', sorted_output)

# 18. Unique values with np.unique()
dup_array = np.array([1, 2, 2, 3, 4, 3, 1, 5])
unique_output = np.unique(dup_array)
print('\nnp.unique ->', unique_output)

np.diag ->
 [[ 4  0  0]
 [ 0  8  0]
 [ 0  0 12]]

np.ravel -> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

np.sort -> [ 1  4  7  9 12]

np.unique -> [1 2 3 4 5]


## 6) Concatenation, splitting and stacking

In [10]:
# 19. Concatenating arrays using np.concatenate()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged = np.concatenate((arr1, arr2))
print('np.concatenate ->', merged)

# 20. Splitting arrays with np.split()
splits = np.split(np.arange(10), 5)
print('\nnp.split ->', splits)

# 21. Vertical stacking with np.vstack()
v_stacked = np.vstack((arr1, arr2))
print('\nnp.vstack ->\n', v_stacked)

# 22. Horizontal stacking with np.hstack()
h_stacked = np.hstack((arr1, arr2))
print('\nnp.hstack ->', h_stacked)

np.concatenate -> [1 2 3 4 5 6]

np.split -> [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

np.vstack ->
 [[1 2 3]
 [4 5 6]]

np.hstack -> [1 2 3 4 5 6]


## 7) Searching, clipping, dot product & cumulative ops

In [11]:
# 23. Conditional extraction with np.where()
cond_arr = np.array([5, 10, 15, 20, 25])
indices = np.where(cond_arr > 12)
print('np.where ->', indices)

# 24. Clipping values with np.clip()
clip_arr = np.array([3, 15, 7, 22, 1])
clipped = np.clip(clip_arr, 5, 15)
print('\nnp.clip ->', clipped)

# 25. Dot product with np.dot()
dot_a = np.array([[1, 2], [3, 4]])
dot_b = np.array([[2, 0], [1, 2]])
dot_result = np.dot(dot_a, dot_b)
print('\nnp.dot ->\n', dot_result)

# 26. Cumulative sum with np.cumsum()
cum_sum = np.cumsum([1, 2, 3, 4, 5])
print('\nnp.cumsum ->', cum_sum)

# 27. Cumulative product with np.cumprod()
cum_prod = np.cumprod([1, 2, 3, 4])
print('\nnp.cumprod ->', cum_prod)

# 28. Generating evenly spaced numbers in log scale with np.logspace()
log_vals = np.logspace(1, 3, 5)
print('\nnp.logspace ->', log_vals)

np.where -> (array([2, 3, 4]),)

np.clip -> [ 5 15  7 15  5]

np.dot ->
 [[ 4  4]
 [10  8]]

np.cumsum -> [ 1  3  6 10 15]

np.cumprod -> [ 1  2  6 24]

np.logspace -> [  10.           31.6227766   100.          316.22776602 1000.        ]


## 8) NaN checks and boolean masking

In [12]:
# 29. Checking NaN values with np.isnan()
nan_arr = np.array([1, 2, np.nan, 4])
print('np.isnan ->', np.isnan(nan_arr))

# 30. Boolean masking with conditions
mask_arr = np.array([10, 15, 20, 25, 30])
masked = mask_arr[mask_arr > 18]
print('\nBoolean Masking ->', masked)

# Bonus: demonstrate masking indices too
print('Indices where >18:', np.where(mask_arr > 18))

np.isnan -> [False False  True False]

Boolean Masking -> [20 25 30]
Indices where >18: (array([2, 3, 4]),)
